name: Code Quality Check

on:
  push:
    branches: [main, develop, master]
  pull_request:
    branches: [main, develop, master]

jobs:
  # This 'quality' job calls your remote workflow
  quality:
    uses: isinghabhishek/.github/.github/workflows/code-quality.yml@c395f81b22d45d75210cfa77265b7829bd569e16
    with:
      run-clippy: true
      run-fmt: true
      run-test: false
