name: Code Quality Check

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  # This 'quality' job calls your remote workflow
  quality:
    uses: ./.github/workflows/code-quality.yml
